# Generated by Django 4.2.6 on 2023-11-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_problem_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
