# Generated by Django 4.2.6 on 2023-11-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_problem_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='bids',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciept',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
