# Generated by Django 4.2.6 on 2023-11-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_problem_scheduled_date_bids_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(blank=True, to='base.worker'),
        ),
    ]
